<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage_home.master" AutoEventWireup="true" CodeFile="des_location.aspx.cs" Inherits="designer_page_des_location" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<div class="content">
    <center>
    <asp:Label ID="Label1" runat="server" Text="PHOTO"></asp:Label><br />
    <asp:FileUpload ID="FileUpload1" runat="server" BorderStyle="Inset"/><br /><br /><br />

    <asp:Label ID="Label2" runat="server" Text="FULL NAME"></asp:Label><br />
    <asp:TextBox ID="TxtName" runat="server"></asp:TextBox><br /><br /><br />

    <asp:Label ID="Label3" runat="server" Text="ADDRESS"></asp:Label><br />
    <asp:TextBox ID="TxtAdd" runat="server" TextMode="MultiLine"></asp:TextBox><br /><br /><br />

    <asp:Label ID="Label5" runat="server" Text="CITY"></asp:Label><br/>
    <asp:TextBox ID="Txtcity" runat="server" ></asp:TextBox><br/><br/><br />

    <asp:Label ID="Label6" runat="server" Text="PINCODE"></asp:Label><br/>
    <asp:TextBox ID="Txtpin" runat="server"></asp:TextBox><br/><br /><br />

    <asp:Label ID="Label4" runat="server" Text="COUNTRY"></asp:Label><br />
    <asp:TextBox ID="TxtCountry" runat="server"></asp:TextBox><br /><br /><br />

    <asp:Button ID="Button1" runat="server" Text="INSERT" OnClick="Button1_Click" /><br /><br /><br />

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="photo" HeaderText="photo" SortExpression="photo" />
            <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
            <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
            <asp:BoundField DataField="pincode" HeaderText="pincode" SortExpression="pincode" />
            <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
            <asp:BoundField DataField="country" HeaderText="country" SortExpression="country" />
        </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [des_location]" 
            UpdateCommand="UPDATE [des_location] Set [photo]=@photo,[name]=@name,[address]=@address,[pincode]=@pincode,[city]=@city,[country]=@country where [id]=@id" DeleteCommand="DELETE from [des_location] where [id]=@id"></asp:SqlDataSource>

    </center>
</div>
    
</asp:Content>

